/*
 * AUTO-GENERATED MACHINE LEARNING MODEL
 * Generated by train_ml.py (scikit-learn + m2cgen).
 * Do not edit manually.
 */

#ifndef SENTINEL_ML_MODEL_H
#define SENTINEL_ML_MODEL_H

#include <math.h>

#include <string.h>
static inline void add_vectors(const double *vec_a, const double *vec_b, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = vec_a[i] + vec_b[i];
}
static inline void mul_vector_number(const double *vec_a, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = vec_a[i] * num;
}
typedef struct {
    double vars[200][2];
} ml_scratch_t;

static inline void score(const double * input, double * output, ml_scratch_t *scr) {
    double *var0 = scr->vars[0];
    double *var1 = scr->vars[1];
    double *var2 = scr->vars[2];
    double *var3 = scr->vars[3];
    double *var4 = scr->vars[4];
    double *var5 = scr->vars[5];
    double *var6 = scr->vars[6];
    double *var7 = scr->vars[7];
    double *var8 = scr->vars[8];
    double *var9 = scr->vars[9];
    double *var10 = scr->vars[10];
    double *var11 = scr->vars[11];
    double *var12 = scr->vars[12];
    double *var13 = scr->vars[13];
    double *var14 = scr->vars[14];
    double *var15 = scr->vars[15];
    double *var16 = scr->vars[16];
    double *var17 = scr->vars[17];
    double *var18 = scr->vars[18];
    double *var19 = scr->vars[19];
    double *var20 = scr->vars[20];
    double *var21 = scr->vars[21];
    double *var22 = scr->vars[22];
    double *var23 = scr->vars[23];
    double *var24 = scr->vars[24];
    double *var25 = scr->vars[25];
    double *var26 = scr->vars[26];
    double *var27 = scr->vars[27];
    double *var28 = scr->vars[28];
    double *var29 = scr->vars[29];
    double *var30 = scr->vars[30];
    double *var31 = scr->vars[31];
    double *var32 = scr->vars[32];
    double *var33 = scr->vars[33];
    double *var34 = scr->vars[34];
    double *var35 = scr->vars[35];
    double *var36 = scr->vars[36];
    double *var37 = scr->vars[37];
    double *var38 = scr->vars[38];
    double *var39 = scr->vars[39];
    double *var40 = scr->vars[40];
    double *var41 = scr->vars[41];
    double *var42 = scr->vars[42];
    double *var43 = scr->vars[43];
    double *var44 = scr->vars[44];
    double *var45 = scr->vars[45];
    double *var46 = scr->vars[46];
    double *var47 = scr->vars[47];
    double *var48 = scr->vars[48];
    double *var49 = scr->vars[49];
    double *var50 = scr->vars[50];
    double *var51 = scr->vars[51];
    double *var52 = scr->vars[52];
    double *var53 = scr->vars[53];
    double *var54 = scr->vars[54];
    double *var55 = scr->vars[55];
    double *var56 = scr->vars[56];
    double *var57 = scr->vars[57];
    double *var58 = scr->vars[58];
    double *var59 = scr->vars[59];
    double *var60 = scr->vars[60];
    double *var61 = scr->vars[61];
    double *var62 = scr->vars[62];
    double *var63 = scr->vars[63];
    double *var64 = scr->vars[64];
    double *var65 = scr->vars[65];
    double *var66 = scr->vars[66];
    double *var67 = scr->vars[67];
    double *var68 = scr->vars[68];
    double *var69 = scr->vars[69];
    double *var70 = scr->vars[70];
    double *var71 = scr->vars[71];
    double *var72 = scr->vars[72];
    double *var73 = scr->vars[73];
    double *var74 = scr->vars[74];
    double *var75 = scr->vars[75];
    double *var76 = scr->vars[76];
    double *var77 = scr->vars[77];
    double *var78 = scr->vars[78];
    double *var79 = scr->vars[79];
    double *var80 = scr->vars[80];
    double *var81 = scr->vars[81];
    double *var82 = scr->vars[82];
    double *var83 = scr->vars[83];
    double *var84 = scr->vars[84];
    double *var85 = scr->vars[85];
    double *var86 = scr->vars[86];
    double *var87 = scr->vars[87];
    double *var88 = scr->vars[88];
    double *var89 = scr->vars[89];
    double *var90 = scr->vars[90];
    double *var91 = scr->vars[91];
    double *var92 = scr->vars[92];
    double *var93 = scr->vars[93];
    double *var94 = scr->vars[94];
    double *var95 = scr->vars[95];
    double *var96 = scr->vars[96];
    double *var97 = scr->vars[97];
    double *var98 = scr->vars[98];
    double *var99 = scr->vars[99];
    double *var100 = scr->vars[100];
    if (input[0] <= 233.887544631958) {
        var100[0] = 1.0; var100[1] = 0.0;
    } else {
        var100[0] = 0.0; var100[1] = 1.0;
    }
    double *var101 = scr->vars[101];
    if (input[6] <= 1.0499794483184814) {
        if (input[11] <= 0.47500258017282704) {
            var101[0] = 1.0; var101[1] = 0.0;
        } else {
            var101[0] = 0.0; var101[1] = 1.0;
        }
    } else {
        if (input[17] <= 50.25019574165344) {
            if (input[15] <= 7797.994567871094) {
                var101[0] = 0.0; var101[1] = 1.0;
            } else {
                var101[0] = 1.0; var101[1] = 0.0;
            }
        } else {
            var101[0] = 0.0; var101[1] = 1.0;
        }
    }
    add_vectors(var100, var101, 2, var99);
    double *var102 = scr->vars[102];
    if (input[18] <= 233.74544143676758) {
        var102[0] = 1.0; var102[1] = 0.0;
    } else {
        var102[0] = 0.0; var102[1] = 1.0;
    }
    add_vectors(var99, var102, 2, var98);
    double *var103 = scr->vars[103];
    if (input[0] <= 233.83381843566895) {
        var103[0] = 1.0; var103[1] = 0.0;
    } else {
        var103[0] = 0.0; var103[1] = 1.0;
    }
    add_vectors(var98, var103, 2, var97);
    double *var104 = scr->vars[104];
    if (input[7] <= 142.49953842163086) {
        var104[0] = 0.0; var104[1] = 1.0;
    } else {
        if (input[16] <= 3866.9168663024902) {
            var104[0] = 0.0; var104[1] = 1.0;
        } else {
            var104[0] = 1.0; var104[1] = 0.0;
        }
    }
    add_vectors(var97, var104, 2, var96);
    double *var105 = scr->vars[105];
    if (input[15] <= 8895.134887695312) {
        var105[0] = 0.0; var105[1] = 1.0;
    } else {
        var105[0] = 1.0; var105[1] = 0.0;
    }
    add_vectors(var96, var105, 2, var95);
    double *var106 = scr->vars[106];
    if (input[5] <= 5.024953603744507) {
        if (input[8] <= 32.99988555908203) {
            var106[0] = 0.0; var106[1] = 1.0;
        } else {
            var106[0] = 1.0; var106[1] = 0.0;
        }
    } else {
        if (input[12] <= 26.5002601146698) {
            var106[0] = 1.0; var106[1] = 0.0;
        } else {
            var106[0] = 0.0; var106[1] = 1.0;
        }
    }
    add_vectors(var95, var106, 2, var94);
    double *var107 = scr->vars[107];
    if (input[0] <= 233.51957893371582) {
        var107[0] = 1.0; var107[1] = 0.0;
    } else {
        var107[0] = 0.0; var107[1] = 1.0;
    }
    add_vectors(var94, var107, 2, var93);
    double *var108 = scr->vars[108];
    if (input[16] <= 4438.6004638671875) {
        var108[0] = 0.0; var108[1] = 1.0;
    } else {
        var108[0] = 1.0; var108[1] = 0.0;
    }
    add_vectors(var93, var108, 2, var92);
    double *var109 = scr->vars[109];
    if (input[15] <= 8871.986450195312) {
        var109[0] = 0.0; var109[1] = 1.0;
    } else {
        var109[0] = 1.0; var109[1] = 0.0;
    }
    add_vectors(var92, var109, 2, var91);
    double *var110 = scr->vars[110];
    if (input[15] <= 8895.446899414062) {
        var110[0] = 0.0; var110[1] = 1.0;
    } else {
        var110[0] = 1.0; var110[1] = 0.0;
    }
    add_vectors(var91, var110, 2, var90);
    double *var111 = scr->vars[111];
    if (input[15] <= 8871.900512695312) {
        var111[0] = 0.0; var111[1] = 1.0;
    } else {
        var111[0] = 1.0; var111[1] = 0.0;
    }
    add_vectors(var90, var111, 2, var89);
    double *var112 = scr->vars[112];
    if (input[6] <= 1.0499939322471619) {
        if (input[5] <= 5.610122203826904) {
            var112[0] = 0.0; var112[1] = 1.0;
        } else {
            var112[0] = 1.0; var112[1] = 0.0;
        }
    } else {
        if (input[9] <= 0.45000752139975475) {
            if (input[12] <= 24.300021708011627) {
                if (input[0] <= 2104.1098366975784) {
                    var112[0] = 1.0; var112[1] = 0.0;
                } else {
                    var112[0] = 0.0; var112[1] = 1.0;
                }
            } else {
                var112[0] = 0.0; var112[1] = 1.0;
            }
        } else {
            var112[0] = 1.0; var112[1] = 0.0;
        }
    }
    add_vectors(var89, var112, 2, var88);
    double *var113 = scr->vars[113];
    if (input[0] <= 233.51957893371582) {
        var113[0] = 1.0; var113[1] = 0.0;
    } else {
        var113[0] = 0.0; var113[1] = 1.0;
    }
    add_vectors(var88, var113, 2, var87);
    double *var114 = scr->vars[114];
    if (input[16] <= 4436.2225341796875) {
        var114[0] = 0.0; var114[1] = 1.0;
    } else {
        var114[0] = 1.0; var114[1] = 0.0;
    }
    add_vectors(var87, var114, 2, var86);
    double *var115 = scr->vars[115];
    if (input[18] <= 233.77303314208984) {
        var115[0] = 1.0; var115[1] = 0.0;
    } else {
        var115[0] = 0.0; var115[1] = 1.0;
    }
    add_vectors(var86, var115, 2, var85);
    double *var116 = scr->vars[116];
    if (input[5] <= 5.024953603744507) {
        if (input[2] <= 0.4350038021802902) {
            var116[0] = 0.0; var116[1] = 1.0;
        } else {
            if (input[16] <= 38586.9361000061) {
                var116[0] = 0.0; var116[1] = 1.0;
            } else {
                var116[0] = 1.0; var116[1] = 0.0;
            }
        }
    } else {
        if (input[0] <= 3273.72572517395) {
            var116[0] = 1.0; var116[1] = 0.0;
        } else {
            var116[0] = 0.0; var116[1] = 1.0;
        }
    }
    add_vectors(var85, var116, 2, var84);
    double *var117 = scr->vars[117];
    if (input[13] <= 67.1998291015625) {
        if (input[18] <= 208.55270910263062) {
            var117[0] = 1.0; var117[1] = 0.0;
        } else {
            var117[0] = 0.0; var117[1] = 1.0;
        }
    } else {
        var117[0] = 1.0; var117[1] = 0.0;
    }
    add_vectors(var84, var117, 2, var83);
    double *var118 = scr->vars[118];
    if (input[0] <= 233.51957893371582) {
        var118[0] = 1.0; var118[1] = 0.0;
    } else {
        var118[0] = 0.0; var118[1] = 1.0;
    }
    add_vectors(var83, var118, 2, var82);
    double *var119 = scr->vars[119];
    if (input[0] <= 233.51773262023926) {
        var119[0] = 1.0; var119[1] = 0.0;
    } else {
        var119[0] = 0.0; var119[1] = 1.0;
    }
    add_vectors(var82, var119, 2, var81);
    double *var120 = scr->vars[120];
    if (input[5] <= 5.0249598026275635) {
        if (input[8] <= 33.000094413757324) {
            var120[0] = 0.0; var120[1] = 1.0;
        } else {
            var120[0] = 1.0; var120[1] = 0.0;
        }
    } else {
        if (input[6] <= 53.0012583732605) {
            var120[0] = 1.0; var120[1] = 0.0;
        } else {
            var120[0] = 0.0; var120[1] = 1.0;
        }
    }
    add_vectors(var81, var120, 2, var80);
    double *var121 = scr->vars[121];
    if (input[15] <= 8872.298461914062) {
        var121[0] = 0.0; var121[1] = 1.0;
    } else {
        var121[0] = 1.0; var121[1] = 0.0;
    }
    add_vectors(var80, var121, 2, var79);
    double *var122 = scr->vars[122];
    if (input[18] <= 233.78040313720703) {
        var122[0] = 1.0; var122[1] = 0.0;
    } else {
        var122[0] = 0.0; var122[1] = 1.0;
    }
    add_vectors(var79, var122, 2, var78);
    double *var123 = scr->vars[123];
    if (input[7] <= 142.50030517578125) {
        var123[0] = 0.0; var123[1] = 1.0;
    } else {
        if (input[18] <= 1650.4581336975098) {
            var123[0] = 1.0; var123[1] = 0.0;
        } else {
            var123[0] = 0.0; var123[1] = 1.0;
        }
    }
    add_vectors(var78, var123, 2, var77);
    double *var124 = scr->vars[124];
    if (input[0] <= 233.88166999816895) {
        var124[0] = 1.0; var124[1] = 0.0;
    } else {
        var124[0] = 0.0; var124[1] = 1.0;
    }
    add_vectors(var77, var124, 2, var76);
    double *var125 = scr->vars[125];
    if (input[16] <= 4445.7657470703125) {
        var125[0] = 0.0; var125[1] = 1.0;
    } else {
        var125[0] = 1.0; var125[1] = 0.0;
    }
    add_vectors(var76, var125, 2, var75);
    double *var126 = scr->vars[126];
    if (input[7] <= 142.50030517578125) {
        var126[0] = 0.0; var126[1] = 1.0;
    } else {
        if (input[15] <= 7787.003471374512) {
            var126[0] = 0.0; var126[1] = 1.0;
        } else {
            var126[0] = 1.0; var126[1] = 0.0;
        }
    }
    add_vectors(var75, var126, 2, var74);
    double *var127 = scr->vars[127];
    if (input[18] <= 233.86540985107422) {
        var127[0] = 1.0; var127[1] = 0.0;
    } else {
        var127[0] = 0.0; var127[1] = 1.0;
    }
    add_vectors(var74, var127, 2, var73);
    double *var128 = scr->vars[128];
    if (input[5] <= 5.0249598026275635) {
        if (input[1] <= 12784.061340332031) {
            var128[0] = 1.0; var128[1] = 0.0;
        } else {
            var128[0] = 0.0; var128[1] = 1.0;
        }
    } else {
        if (input[6] <= 53.0012583732605) {
            var128[0] = 1.0; var128[1] = 0.0;
        } else {
            var128[0] = 0.0; var128[1] = 1.0;
        }
    }
    add_vectors(var73, var128, 2, var72);
    double *var129 = scr->vars[129];
    if (input[16] <= 4438.060363769531) {
        var129[0] = 0.0; var129[1] = 1.0;
    } else {
        var129[0] = 1.0; var129[1] = 0.0;
    }
    add_vectors(var72, var129, 2, var71);
    double *var130 = scr->vars[130];
    if (input[16] <= 4435.682434082031) {
        var130[0] = 0.0; var130[1] = 1.0;
    } else {
        var130[0] = 1.0; var130[1] = 0.0;
    }
    add_vectors(var71, var130, 2, var70);
    double *var131 = scr->vars[131];
    if (input[18] <= 233.74544143676758) {
        var131[0] = 1.0; var131[1] = 0.0;
    } else {
        var131[0] = 0.0; var131[1] = 1.0;
    }
    add_vectors(var70, var131, 2, var69);
    double *var132 = scr->vars[132];
    if (input[18] <= 233.81247329711914) {
        var132[0] = 1.0; var132[1] = 0.0;
    } else {
        var132[0] = 0.0; var132[1] = 1.0;
    }
    add_vectors(var69, var132, 2, var68);
    double *var133 = scr->vars[133];
    if (input[7] <= 142.50030517578125) {
        var133[0] = 0.0; var133[1] = 1.0;
    } else {
        if (input[16] <= 3866.9168663024902) {
            var133[0] = 0.0; var133[1] = 1.0;
        } else {
            var133[0] = 1.0; var133[1] = 0.0;
        }
    }
    add_vectors(var68, var133, 2, var67);
    double *var134 = scr->vars[134];
    if (input[18] <= 235.11890029907227) {
        var134[0] = 1.0; var134[1] = 0.0;
    } else {
        var134[0] = 0.0; var134[1] = 1.0;
    }
    add_vectors(var67, var134, 2, var66);
    double *var135 = scr->vars[135];
    if (input[16] <= 4443.588073730469) {
        var135[0] = 0.0; var135[1] = 1.0;
    } else {
        var135[0] = 1.0; var135[1] = 0.0;
    }
    add_vectors(var66, var135, 2, var65);
    double *var136 = scr->vars[136];
    if (input[8] <= 33.00015926361084) {
        if (input[6] <= 0.9499929547309875) {
            var136[0] = 1.0; var136[1] = 0.0;
        } else {
            if (input[0] <= 203.28580915927887) {
                var136[0] = 1.0; var136[1] = 0.0;
            } else {
                var136[0] = 0.0; var136[1] = 1.0;
            }
        }
    } else {
        var136[0] = 1.0; var136[1] = 0.0;
    }
    add_vectors(var65, var136, 2, var64);
    double *var137 = scr->vars[137];
    if (input[1] <= 98615.99609375) {
        if (input[8] <= 7.125203371047974) {
            var137[0] = 0.0; var137[1] = 1.0;
        } else {
            var137[0] = 1.0; var137[1] = 0.0;
        }
    } else {
        var137[0] = 0.0; var137[1] = 1.0;
    }
    add_vectors(var64, var137, 2, var63);
    double *var138 = scr->vars[138];
    if (input[18] <= 234.02853775024414) {
        var138[0] = 1.0; var138[1] = 0.0;
    } else {
        var138[0] = 0.0; var138[1] = 1.0;
    }
    add_vectors(var63, var138, 2, var62);
    double *var139 = scr->vars[139];
    if (input[15] <= 8871.986450195312) {
        var139[0] = 0.0; var139[1] = 1.0;
    } else {
        var139[0] = 1.0; var139[1] = 0.0;
    }
    add_vectors(var62, var139, 2, var61);
    double *var140 = scr->vars[140];
    if (input[1] <= 98637.17578125) {
        if (input[7] <= 121.49876022338867) {
            var140[0] = 0.0; var140[1] = 1.0;
        } else {
            var140[0] = 1.0; var140[1] = 0.0;
        }
    } else {
        var140[0] = 0.0; var140[1] = 1.0;
    }
    add_vectors(var61, var140, 2, var60);
    double *var141 = scr->vars[141];
    if (input[8] <= 33.000094413757324) {
        if (input[0] <= 203.60189497470856) {
            var141[0] = 1.0; var141[1] = 0.0;
        } else {
            var141[0] = 0.0; var141[1] = 1.0;
        }
    } else {
        var141[0] = 1.0; var141[1] = 0.0;
    }
    add_vectors(var60, var141, 2, var59);
    double *var142 = scr->vars[142];
    if (input[18] <= 233.81247329711914) {
        var142[0] = 1.0; var142[1] = 0.0;
    } else {
        var142[0] = 0.0; var142[1] = 1.0;
    }
    add_vectors(var59, var142, 2, var58);
    double *var143 = scr->vars[143];
    if (input[0] <= 233.51957893371582) {
        var143[0] = 1.0; var143[1] = 0.0;
    } else {
        var143[0] = 0.0; var143[1] = 1.0;
    }
    add_vectors(var58, var143, 2, var57);
    double *var144 = scr->vars[144];
    if (input[16] <= 4436.2225341796875) {
        var144[0] = 0.0; var144[1] = 1.0;
    } else {
        var144[0] = 1.0; var144[1] = 0.0;
    }
    add_vectors(var57, var144, 2, var56);
    double *var145 = scr->vars[145];
    if (input[16] <= 4438.6004638671875) {
        var145[0] = 0.0; var145[1] = 1.0;
    } else {
        var145[0] = 1.0; var145[1] = 0.0;
    }
    add_vectors(var56, var145, 2, var55);
    double *var146 = scr->vars[146];
    if (input[7] <= 142.50030517578125) {
        var146[0] = 0.0; var146[1] = 1.0;
    } else {
        if (input[0] <= 1651.3182544708252) {
            var146[0] = 1.0; var146[1] = 0.0;
        } else {
            var146[0] = 0.0; var146[1] = 1.0;
        }
    }
    add_vectors(var55, var146, 2, var54);
    double *var147 = scr->vars[147];
    if (input[16] <= 4436.2225341796875) {
        var147[0] = 0.0; var147[1] = 1.0;
    } else {
        var147[0] = 1.0; var147[1] = 0.0;
    }
    add_vectors(var54, var147, 2, var53);
    double *var148 = scr->vars[148];
    if (input[15] <= 8895.446899414062) {
        var148[0] = 0.0; var148[1] = 1.0;
    } else {
        var148[0] = 1.0; var148[1] = 0.0;
    }
    add_vectors(var53, var148, 2, var52);
    double *var149 = scr->vars[149];
    if (input[0] <= 233.48994827270508) {
        var149[0] = 1.0; var149[1] = 0.0;
    } else {
        var149[0] = 0.0; var149[1] = 1.0;
    }
    add_vectors(var52, var149, 2, var51);
    double *var150 = scr->vars[150];
    if (input[0] <= 233.51773262023926) {
        var150[0] = 1.0; var150[1] = 0.0;
    } else {
        var150[0] = 0.0; var150[1] = 1.0;
    }
    add_vectors(var51, var150, 2, var50);
    double *var151 = scr->vars[151];
    if (input[1] <= 98850.19140625) {
        if (input[9] <= 195.50439023971558) {
            var151[0] = 1.0; var151[1] = 0.0;
        } else {
            var151[0] = 0.0; var151[1] = 1.0;
        }
    } else {
        var151[0] = 0.0; var151[1] = 1.0;
    }
    add_vectors(var50, var151, 2, var49);
    double *var152 = scr->vars[152];
    if (input[15] <= 8872.298461914062) {
        var152[0] = 0.0; var152[1] = 1.0;
    } else {
        var152[0] = 1.0; var152[1] = 0.0;
    }
    add_vectors(var49, var152, 2, var48);
    double *var153 = scr->vars[153];
    if (input[17] <= 50.25050091743469) {
        if (input[15] <= 8872.298461914062) {
            var153[0] = 0.0; var153[1] = 1.0;
        } else {
            var153[0] = 1.0; var153[1] = 0.0;
        }
    } else {
        var153[0] = 0.0; var153[1] = 1.0;
    }
    add_vectors(var48, var153, 2, var47);
    double *var154 = scr->vars[154];
    if (input[0] <= 233.51957893371582) {
        var154[0] = 1.0; var154[1] = 0.0;
    } else {
        var154[0] = 0.0; var154[1] = 1.0;
    }
    add_vectors(var47, var154, 2, var46);
    double *var155 = scr->vars[155];
    if (input[15] <= 8871.986450195312) {
        var155[0] = 0.0; var155[1] = 1.0;
    } else {
        var155[0] = 1.0; var155[1] = 0.0;
    }
    add_vectors(var46, var155, 2, var45);
    double *var156 = scr->vars[156];
    if (input[0] <= 233.48994827270508) {
        var156[0] = 1.0; var156[1] = 0.0;
    } else {
        var156[0] = 0.0; var156[1] = 1.0;
    }
    add_vectors(var45, var156, 2, var44);
    double *var157 = scr->vars[157];
    if (input[5] <= 5.0249598026275635) {
        if (input[10] <= 0.04500308341351911) {
            var157[0] = 0.0; var157[1] = 1.0;
        } else {
            if (input[11] <= 2.9999775886535645) {
                var157[0] = 1.0; var157[1] = 0.0;
            } else {
                var157[0] = 0.0; var157[1] = 1.0;
            }
        }
    } else {
        if (input[0] <= 3270.1218280792236) {
            var157[0] = 1.0; var157[1] = 0.0;
        } else {
            var157[0] = 0.0; var157[1] = 1.0;
        }
    }
    add_vectors(var44, var157, 2, var43);
    double *var158 = scr->vars[158];
    if (input[1] <= 98615.99609375) {
        if (input[0] <= 233.51957893371582) {
            var158[0] = 1.0; var158[1] = 0.0;
        } else {
            var158[0] = 0.0; var158[1] = 1.0;
        }
    } else {
        var158[0] = 0.0; var158[1] = 1.0;
    }
    add_vectors(var43, var158, 2, var42);
    double *var159 = scr->vars[159];
    if (input[1] <= 98615.99609375) {
        if (input[15] <= 8871.986450195312) {
            var159[0] = 0.0; var159[1] = 1.0;
        } else {
            var159[0] = 1.0; var159[1] = 0.0;
        }
    } else {
        var159[0] = 0.0; var159[1] = 1.0;
    }
    add_vectors(var42, var159, 2, var41);
    double *var160 = scr->vars[160];
    if (input[7] <= 142.50030517578125) {
        var160[0] = 0.0; var160[1] = 1.0;
    } else {
        if (input[0] <= 1653.4969654083252) {
            var160[0] = 1.0; var160[1] = 0.0;
        } else {
            var160[0] = 0.0; var160[1] = 1.0;
        }
    }
    add_vectors(var41, var160, 2, var40);
    double *var161 = scr->vars[161];
    if (input[7] <= 142.5004768371582) {
        var161[0] = 0.0; var161[1] = 1.0;
    } else {
        if (input[0] <= 1651.3182544708252) {
            var161[0] = 1.0; var161[1] = 0.0;
        } else {
            var161[0] = 0.0; var161[1] = 1.0;
        }
    }
    add_vectors(var40, var161, 2, var39);
    double *var162 = scr->vars[162];
    if (input[16] <= 4438.6004638671875) {
        var162[0] = 0.0; var162[1] = 1.0;
    } else {
        var162[0] = 1.0; var162[1] = 0.0;
    }
    add_vectors(var39, var162, 2, var38);
    double *var163 = scr->vars[163];
    if (input[0] <= 233.48994827270508) {
        var163[0] = 1.0; var163[1] = 0.0;
    } else {
        var163[0] = 0.0; var163[1] = 1.0;
    }
    add_vectors(var38, var163, 2, var37);
    double *var164 = scr->vars[164];
    if (input[15] <= 8872.298461914062) {
        var164[0] = 0.0; var164[1] = 1.0;
    } else {
        var164[0] = 1.0; var164[1] = 0.0;
    }
    add_vectors(var37, var164, 2, var36);
    double *var165 = scr->vars[165];
    if (input[15] <= 8872.298461914062) {
        var165[0] = 0.0; var165[1] = 1.0;
    } else {
        var165[0] = 1.0; var165[1] = 0.0;
    }
    add_vectors(var36, var165, 2, var35);
    double *var166 = scr->vars[166];
    if (input[7] <= 142.50030517578125) {
        var166[0] = 0.0; var166[1] = 1.0;
    } else {
        if (input[12] <= 26.5002601146698) {
            if (input[7] <= 1372.5146484375) {
                var166[0] = 1.0; var166[1] = 0.0;
            } else {
                var166[0] = 0.0; var166[1] = 1.0;
            }
        } else {
            var166[0] = 0.0; var166[1] = 1.0;
        }
    }
    add_vectors(var35, var166, 2, var34);
    double *var167 = scr->vars[167];
    if (input[15] <= 8872.298461914062) {
        var167[0] = 0.0; var167[1] = 1.0;
    } else {
        var167[0] = 1.0; var167[1] = 0.0;
    }
    add_vectors(var34, var167, 2, var33);
    double *var168 = scr->vars[168];
    if (input[18] <= 233.74544143676758) {
        var168[0] = 1.0; var168[1] = 0.0;
    } else {
        var168[0] = 0.0; var168[1] = 1.0;
    }
    add_vectors(var33, var168, 2, var32);
    double *var169 = scr->vars[169];
    if (input[16] <= 4438.6004638671875) {
        var169[0] = 0.0; var169[1] = 1.0;
    } else {
        var169[0] = 1.0; var169[1] = 0.0;
    }
    add_vectors(var32, var169, 2, var31);
    double *var170 = scr->vars[170];
    if (input[5] <= 5.025117635726929) {
        if (input[15] <= 78284.46203613281) {
            var170[0] = 0.0; var170[1] = 1.0;
        } else {
            var170[0] = 1.0; var170[1] = 0.0;
        }
    } else {
        if (input[17] <= 50.25047588348389) {
            var170[0] = 1.0; var170[1] = 0.0;
        } else {
            var170[0] = 0.0; var170[1] = 1.0;
        }
    }
    add_vectors(var31, var170, 2, var30);
    double *var171 = scr->vars[171];
    if (input[15] <= 8872.298461914062) {
        var171[0] = 0.0; var171[1] = 1.0;
    } else {
        var171[0] = 1.0; var171[1] = 0.0;
    }
    add_vectors(var30, var171, 2, var29);
    double *var172 = scr->vars[172];
    if (input[18] <= 233.74544143676758) {
        var172[0] = 1.0; var172[1] = 0.0;
    } else {
        var172[0] = 0.0; var172[1] = 1.0;
    }
    add_vectors(var29, var172, 2, var28);
    double *var173 = scr->vars[173];
    if (input[18] <= 233.74544143676758) {
        var173[0] = 1.0; var173[1] = 0.0;
    } else {
        var173[0] = 0.0; var173[1] = 1.0;
    }
    add_vectors(var28, var173, 2, var27);
    double *var174 = scr->vars[174];
    if (input[16] <= 4436.2225341796875) {
        var174[0] = 0.0; var174[1] = 1.0;
    } else {
        var174[0] = 1.0; var174[1] = 0.0;
    }
    add_vectors(var27, var174, 2, var26);
    double *var175 = scr->vars[175];
    if (input[15] <= 8872.298461914062) {
        var175[0] = 0.0; var175[1] = 1.0;
    } else {
        var175[0] = 1.0; var175[1] = 0.0;
    }
    add_vectors(var26, var175, 2, var25);
    double *var176 = scr->vars[176];
    if (input[0] <= 233.8356647491455) {
        var176[0] = 1.0; var176[1] = 0.0;
    } else {
        var176[0] = 0.0; var176[1] = 1.0;
    }
    add_vectors(var25, var176, 2, var24);
    double *var177 = scr->vars[177];
    if (input[15] <= 8872.298461914062) {
        var177[0] = 0.0; var177[1] = 1.0;
    } else {
        var177[0] = 1.0; var177[1] = 0.0;
    }
    add_vectors(var24, var177, 2, var23);
    double *var178 = scr->vars[178];
    if (input[0] <= 233.88166999816895) {
        var178[0] = 1.0; var178[1] = 0.0;
    } else {
        var178[0] = 0.0; var178[1] = 1.0;
    }
    add_vectors(var23, var178, 2, var22);
    double *var179 = scr->vars[179];
    if (input[16] <= 4436.2225341796875) {
        var179[0] = 0.0; var179[1] = 1.0;
    } else {
        var179[0] = 1.0; var179[1] = 0.0;
    }
    add_vectors(var22, var179, 2, var21);
    double *var180 = scr->vars[180];
    if (input[15] <= 8895.446899414062) {
        var180[0] = 0.0; var180[1] = 1.0;
    } else {
        var180[0] = 1.0; var180[1] = 0.0;
    }
    add_vectors(var21, var180, 2, var20);
    double *var181 = scr->vars[181];
    if (input[1] <= 98615.99609375) {
        if (input[19] <= 190.5500453710556) {
            var181[0] = 1.0; var181[1] = 0.0;
        } else {
            var181[0] = 0.0; var181[1] = 1.0;
        }
    } else {
        var181[0] = 0.0; var181[1] = 1.0;
    }
    add_vectors(var20, var181, 2, var19);
    double *var182 = scr->vars[182];
    if (input[10] <= 0.009000659799255573) {
        if (input[1] <= 12630.09765625) {
            var182[0] = 1.0; var182[1] = 0.0;
        } else {
            var182[0] = 0.0; var182[1] = 1.0;
        }
    } else {
        if (input[0] <= 1246.2762470245361) {
            var182[0] = 1.0; var182[1] = 0.0;
        } else {
            var182[0] = 0.0; var182[1] = 1.0;
        }
    }
    add_vectors(var19, var182, 2, var18);
    double *var183 = scr->vars[183];
    if (input[18] <= 233.89748001098633) {
        var183[0] = 1.0; var183[1] = 0.0;
    } else {
        var183[0] = 0.0; var183[1] = 1.0;
    }
    add_vectors(var18, var183, 2, var17);
    double *var184 = scr->vars[184];
    if (input[16] <= 4438.6004638671875) {
        var184[0] = 0.0; var184[1] = 1.0;
    } else {
        var184[0] = 1.0; var184[1] = 0.0;
    }
    add_vectors(var17, var184, 2, var16);
    double *var185 = scr->vars[185];
    if (input[8] <= 33.000094413757324) {
        if (input[17] <= 0.9499842822551727) {
            var185[0] = 1.0; var185[1] = 0.0;
        } else {
            if (input[7] <= 232.5002098083496) {
                var185[0] = 0.0; var185[1] = 1.0;
            } else {
                if (input[7] <= 694.9928741455078) {
                    var185[0] = 1.0; var185[1] = 0.0;
                } else {
                    var185[0] = 0.0; var185[1] = 1.0;
                }
            }
        }
    } else {
        var185[0] = 1.0; var185[1] = 0.0;
    }
    add_vectors(var16, var185, 2, var15);
    double *var186 = scr->vars[186];
    if (input[18] <= 233.85803985595703) {
        var186[0] = 1.0; var186[1] = 0.0;
    } else {
        var186[0] = 0.0; var186[1] = 1.0;
    }
    add_vectors(var15, var186, 2, var14);
    double *var187 = scr->vars[187];
    if (input[1] <= 98753.4453125) {
        if (input[4] <= 5.700017929077148) {
            var187[0] = 1.0; var187[1] = 0.0;
        } else {
            if (input[7] <= 256.5445613861084) {
                var187[0] = 0.0; var187[1] = 1.0;
            } else {
                var187[0] = 1.0; var187[1] = 0.0;
            }
        }
    } else {
        var187[0] = 0.0; var187[1] = 1.0;
    }
    add_vectors(var14, var187, 2, var13);
    double *var188 = scr->vars[188];
    if (input[8] <= 33.00002384185791) {
        if (input[15] <= 194262.4620361328) {
            var188[0] = 0.0; var188[1] = 1.0;
        } else {
            var188[0] = 1.0; var188[1] = 0.0;
        }
    } else {
        var188[0] = 1.0; var188[1] = 0.0;
    }
    add_vectors(var13, var188, 2, var12);
    double *var189 = scr->vars[189];
    if (input[15] <= 8871.986450195312) {
        var189[0] = 0.0; var189[1] = 1.0;
    } else {
        var189[0] = 1.0; var189[1] = 0.0;
    }
    add_vectors(var12, var189, 2, var11);
    double *var190 = scr->vars[190];
    if (input[15] <= 8901.875610351562) {
        var190[0] = 0.0; var190[1] = 1.0;
    } else {
        var190[0] = 1.0; var190[1] = 0.0;
    }
    add_vectors(var11, var190, 2, var10);
    double *var191 = scr->vars[191];
    if (input[1] <= 98753.4453125) {
        if (input[9] <= 195.5022578239441) {
            var191[0] = 1.0; var191[1] = 0.0;
        } else {
            var191[0] = 0.0; var191[1] = 1.0;
        }
    } else {
        var191[0] = 0.0; var191[1] = 1.0;
    }
    add_vectors(var10, var191, 2, var9);
    double *var192 = scr->vars[192];
    if (input[1] <= 98895.51171875) {
        if (input[9] <= 195.51374340057373) {
            var192[0] = 1.0; var192[1] = 0.0;
        } else {
            var192[0] = 0.0; var192[1] = 1.0;
        }
    } else {
        var192[0] = 0.0; var192[1] = 1.0;
    }
    add_vectors(var9, var192, 2, var8);
    double *var193 = scr->vars[193];
    if (input[1] <= 98637.17578125) {
        if (input[19] <= 190.55329656600952) {
            var193[0] = 1.0; var193[1] = 0.0;
        } else {
            var193[0] = 0.0; var193[1] = 1.0;
        }
    } else {
        var193[0] = 0.0; var193[1] = 1.0;
    }
    add_vectors(var8, var193, 2, var7);
    double *var194 = scr->vars[194];
    if (input[16] <= 4438.060363769531) {
        var194[0] = 0.0; var194[1] = 1.0;
    } else {
        var194[0] = 1.0; var194[1] = 0.0;
    }
    add_vectors(var7, var194, 2, var6);
    double *var195 = scr->vars[195];
    if (input[10] <= 0.00900075013754531) {
        if (input[1] <= 12631.1328125) {
            var195[0] = 1.0; var195[1] = 0.0;
        } else {
            var195[0] = 0.0; var195[1] = 1.0;
        }
    } else {
        if (input[18] <= 1245.798698425293) {
            var195[0] = 1.0; var195[1] = 0.0;
        } else {
            var195[0] = 0.0; var195[1] = 1.0;
        }
    }
    add_vectors(var6, var195, 2, var5);
    double *var196 = scr->vars[196];
    if (input[15] <= 8872.298461914062) {
        var196[0] = 0.0; var196[1] = 1.0;
    } else {
        var196[0] = 1.0; var196[1] = 0.0;
    }
    add_vectors(var5, var196, 2, var4);
    double *var197 = scr->vars[197];
    if (input[12] <= 1.0500118136405945) {
        if (input[5] <= 5.609963417053223) {
            var197[0] = 0.0; var197[1] = 1.0;
        } else {
            var197[0] = 1.0; var197[1] = 0.0;
        }
    } else {
        if (input[17] <= 50.25050091743469) {
            var197[0] = 1.0; var197[1] = 0.0;
        } else {
            var197[0] = 0.0; var197[1] = 1.0;
        }
    }
    add_vectors(var4, var197, 2, var3);
    double *var198 = scr->vars[198];
    if (input[0] <= 233.51957893371582) {
        var198[0] = 1.0; var198[1] = 0.0;
    } else {
        var198[0] = 0.0; var198[1] = 1.0;
    }
    add_vectors(var3, var198, 2, var2);
    double *var199 = scr->vars[199];
    if (input[0] <= 233.51957893371582) {
        var199[0] = 1.0; var199[1] = 0.0;
    } else {
        var199[0] = 0.0; var199[1] = 1.0;
    }
    add_vectors(var2, var199, 2, var1);
    mul_vector_number(var1, 0.01, 2, var0);
    output[0] = var0[0]; output[1] = var0[1];
}

/*
 * Wrapper for Sentinel 20-feature vector.
 * Maps sentinel_feature_vector_t to the model input array.
 * Returns probability of attack [0.0 - 1.0].
 */
static inline double run_ml_inference(const sentinel_feature_vector_t *f, ml_scratch_t *scr) {
    double input[20];
    double output[2];

    input[0]  = f->packets_per_second;
    input[1]  = f->bytes_per_second;
    input[2]  = f->syn_ratio;
    input[3]  = f->rst_ratio;
    input[4]  = f->dst_port_entropy;
    input[5]  = f->payload_byte_entropy;
    input[6]  = (double)f->unique_dst_ports;
    input[7]  = f->avg_packet_size;
    input[8]  = f->stddev_packet_size;
    input[9]  = (double)f->http_request_count;
    input[10] = f->fin_ratio;
    input[11] = f->src_port_entropy;
    input[12] = (double)f->unique_src_ports;
    input[13] = f->avg_ttl;
    input[14] = f->stddev_ttl;
    input[15] = f->avg_iat_us;
    input[16] = f->stddev_iat_us;
    input[17] = (double)f->src_total_flows;
    input[18] = f->src_packets_per_second;
    input[19] = (double)f->dns_query_count;

    score(input, output, scr);
    return output[1];
}

#endif /* SENTINEL_ML_MODEL_H */
